version: "3.1"

services:
  db:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    #    volumes:
    # - ./sftoolAPI:/data/db
    environment:
      - MONGO_INITDB_DATABASE= SingleProjectBusiness
    ports:
      - 27017:27017
